
<../../mkfiles/mkconfig

TARG=2a

OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../2c/2.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

LIBS=cc bio 9		# order is important

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone

YFLAGS=-D1 -d

lex.$O:	../cc/macbody ../cc/lexbody

